const supportedChains = [
  {
    name: "Ethereum Mainnet",
    chainId: 1,
    rpc: "https://mainnet.infura.io/v3/de9db908d55647368373fdb42546104e",
    wssRpc: "wss://mainnet.infura.io/ws/v3/de9db908d55647368373fdb42546104e",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl:
      "https://bundler.biconomy.io/api/v2/1/nJPK7B3ru.dd7f7861-190d-41bd-af80-6877f74b8f44",
    paymasterUrl:
      "https://paymaster.biconomy.io/api/v1/1/4nUU0EmQ6.2c5c625b-dc68-4ad4-8d05-0e7a399590fd",
    isMainnet: true,
    isL2: false,
    isERC20GasPaymentSupported: true,
    isEnabled: true,
    explorerUrl: "https://etherscan.io/tx/",
  },
  {
    name: "Ethereum Goerli",
    chainId: 5,
    rpc: "https://goerli.infura.io/v3/de9db908d55647368373fdb42546104e",
    wssRpc: "wss://goerli.infura.io/ws/v3/de9db908d55647368373fdb42546104e",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl:
      "https://bundler.biconomy.io/api/v2/5/nJPK7B3ru.dd7f7861-190d-41bd-af80-6877f74b8f44",
    paymasterUrl:
      "https://paymaster.biconomy.io/api/v1/5/rjhoCQp58.3c5dc789-ff1e-445c-a60d-fb7b2ecc6bd9",
    isMainnet: false,
    isL2: false,
    isERC20GasPaymentSupported: true,
    isEnabled: true,
    explorerUrl: "https://goerli.etherscan.io/tx/",
  },
  {
    name: "Polygon Mainnet",
    chainId: 137,
    rpc: "https://polygon-mainnet.infura.io/v3/de9db908d55647368373fdb42546104e",
    wssRpc:
      "wss://polygon-mainnet.infura.io/ws/v3/de9db908d55647368373fdb42546104e",
    nativeAsset: "MATIC",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png",
    bundlerUrl:
      "https://bundler.biconomy.io/api/v2/137/nJPK7B3ru.dd7f7861-190d-41bd-af80-6877f74b8f44",
    paymasterUrl:
      "https://paymaster.biconomy.io/api/v1/137/UYATlrlJ9.d1efbad1-1158-4156-ae07-324726431f69",
    isMainnet: true,
    isL2: false,
    isERC20GasPaymentSupported: true,
    isEnabled: true,
    explorerUrl: "https://polygonscan.com/tx/",
  },
  {
    name: "Polygon Mumbai",
    chainId: 80001,
    rpc: "https://polygon-mumbai.infura.io/v3/513aa168689a498fb1a502b99b8793ae",
    wssRpc:
      "wss://polygon-mumbai.infura.io/ws/v3/de9db908d55647368373fdb42546104e",
    nativeAsset: "MATIC",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png",
    bundlerUrl:
      "https://bundler.biconomy.io/api/v2/80001/nJPK7B3ru.dd7f7861-190d-41bd-af80-6877f74b8f44",
    paymasterUrl:
      "https://paymaster.biconomy.io/api/v1/80001/UYATlrlJ9.d1efbad1-1158-4156-ae07-324726431f69",
    isMainnet: false,
    isL2: false,
    isERC20GasPaymentSupported: true,
    isEnabled: true,
    explorerUrl: "https://mumbai.polygonscan.com/tx/",
  },
  {
    name: "Arbitrum One Mainnet",
    chainId: 42161,
    rpc: "https://arbitrum-one.publicnode.com",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/11841.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: true,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://arbiscan.io/tx/",
  },
  {
    name: "Arbitrum Nova Mainnet",
    chainId: 42170,
    rpc: "https://nova.arbitrum.io/rpc",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/11841.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: true,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://nova.arbiscan.io/tx/",
  },
  {
    name: "Polygon ZKEVM Mainnet",
    chainId: 1101,
    rpc: "https://zkevm-rpc.com",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: true,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://zkevm.polygonscan.com/tx/",
  },
  {
    name: "BSC Mainnet",
    chainId: 56,
    rpc: "https://bsc.publicnode.com",
    wssRpc: "",
    nativeAsset: "BNB",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: true,
    isL2: false,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://bscscan.com/tx/",
  },
  {
    name: "Optimism Mainnet",
    chainId: 10,
    rpc: "https://mainnet.optimism.io",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/11840.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: true,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://optimistic.etherscan.io/tx/",
  },
  {
    name: "Avalanche Mainnet",
    chainId: 43114,
    rpc: "https://api.avax.network/ext/bc/C/rpc",
    wssRpc: "",
    nativeAsset: "AVAX",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: true,
    isL2: false,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://snowtrace.io/tx/",
  },
  {
    name: "Base Mainnet",
    chainId: 8453,
    rpc: "https://developer-access-mainnet.base.org",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri:
      "https://pbs.twimg.com/profile_images/1632431836096782338/W-9qsu1e_400x400.jpg",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: true,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://basescan.org/tx/",
  },
  {
    name: "Moon Beam Mainnet",
    chainId: 1284,
    rpc: "https://rpc.api.moonbeam.network",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/6836.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: true,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://moonscan.io/tx/",
  },
  {
    name: "Linea Mainnet",
    chainId: 59144,
    rpc: "https://linea-mainnet.infura.io/v3/8af40d61a66047ca8294a0bb43b958fa",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/27657.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: true,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://lineascan.build/tx/",
  },
  {
    name: "Mantle Mainnet",
    chainId: 5000,
    rpc: "https://rpc.mantle.xyz",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/27075.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: true,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://mantlescan.info/tx/",
  },
  {
    name: "opBNB Mainnet",
    chainId: 204,
    rpc: "https://opbnb-mainnet-rpc.bnbchain.org",
    wssRpc: "",
    nativeAsset: "BNB",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/11840.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: true,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://opbnb.bscscan.com/tx/",
  },
  {
    name: "BSC Testnet",
    chainId: 97,
    rpc: "https://data-seed-prebsc-1-s1.binance.org:8545",
    wssRpc: "",
    nativeAsset: "BNB",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: false,
    isL2: false,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://testnet.bscscan.com/tx/",
  },
  {
    name: "Polygon ZKEVM Testnet",
    chainId: 1442,
    rpc: "https://rpc.public.zkevm-test.net",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: false,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://testnet-zkevm.polygonscan.com/tx/",
  },
  {
    name: "Arbitrum Goerli Testnet",
    chainId: 421613,
    rpc: "https://goerli-rollup.arbitrum.io/rpc",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/11841.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: false,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "",
  },
  {
    name: "Optimism Goerli Testnet",
    chainId: 420,
    rpc: "https://goerli.optimism.io",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/11840.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: false,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://goerli-optimism.etherscan.io/tx/",
  },
  {
    name: "Avalanche Testnet",
    chainId: 43113,
    rpc: "https://api.avax-test.network/ext/bc/C/rpc",
    wssRpc: "",
    nativeAsset: "AVAX",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: false,
    isL2: false,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://testnet.avascan.info/blockchain/c/tx/",
  },
  {
    name: "Base Goerli Testnet",
    chainId: 84531,
    rpc: "https://goerli.base.org",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri:
      "https://pbs.twimg.com/profile_images/1632431836096782338/W-9qsu1e_400x400.jpg",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: false,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://goerli.basescan.org/tx/",
  },
  {
    name: "Linea Testnet",
    chainId: 59140,
    rpc: "https://rpc.goerli.linea.build",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/27657.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: false,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://explorer.linea.build/",
  },
  {
    name: "Moonbase Alpha Testnet",
    chainId: 1287,
    rpc: "https://rpc.testnet.moonbeam.network",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/6836.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: false,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://moonbase.moonscan.io/tx/",
  },
  {
    name: "Mantle Testnet",
    chainId: 5001,
    rpc: "https://rpc.testnet.mantle.xyz",
    wssRpc: "",
    nativeAsset: "ETH",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/27075.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: false,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "https://testnet.mantlescan.org/tx/",
  },
  {
    name: "Optimism Binance Testnet",
    chainId: 5611,
    rpc: "https://opbnb-testnet-rpc.bnbchain.org",
    wssRpc: "",
    nativeAsset: "BNB",
    chainUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/11840.png",
    coinUri: "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
    bundlerUrl: "",
    paymasterUrl: "",
    isMainnet: false,
    isL2: true,
    isERC20GasPaymentSupported: true,
    isEnabled: false,
    explorerUrl: "",
  },
];

export default supportedChains;
